# Generated by Django 4.0.3 on 2022-04-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgerapp', '0002_customerdetails_ingredient_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderTime',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
